# Generated by Django 5.0.3 on 2024-04-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
