# Generated by Django 5.0.3 on 2024-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_result_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
