# Generated by Django 5.0.3 on 2024-05-27 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_assignment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 10, 30, 52, 158598)),
        ),
        migrations.AddField(
            model_name='assignment',
            name='courses',
            field=models.ManyToManyField(related_name='assignments', to='api.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='api.course'),
        ),
    ]
