# Generated by Django 5.0.3 on 2024-05-28 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_course_course_code_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 14, 1, 13, 631705)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='key',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.TextField(default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='url',
            field=models.TextField(default='', null=True),
        ),
    ]
