# Generated by Django 5.0.3 on 2024-06-02 07:56

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reason',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 7, 56, 50, 34427)),
        ),
    ]
